apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ .Release.Name }}-spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.hub.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
