{{ if .Values.hub.extraConfig.sparknamespace }}
{{- $sparkConfig := (lookup "v1" "ConfigMap" .Values.hub.extraConfig.sparknamespace "spark-defaults") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  spark-defaults.conf: |
    test={{ $sparkConfig }}
